[[feeds]]
name = 'Generations from Exile Tribe (Band)'
url = 'https://archiveofourown.org/works?work_search%5Bsort_column%5D=revised_at&work_search%5Bother_tag_names%5D=&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=zh&commit=Sort+and+Filter&tag_id=Generations+from+Exile+Tribe+%28Band%29'

[[feeds]]
name = 'The Rampage from Exile Tribe (Band)'
url = 'https://archiveofourown.org/works?work_search%5Bsort_column%5D=revised_at&work_search%5Bother_tag_names%5D=&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=zh&commit=Sort+and+Filter&tag_id=The+Rampage+from+Exile+Tribe+%28Band%29'

[[feeds]]
name = 'Fantastics from Exile Tribe (Band)'
url = 'https://archiveofourown.org/works?work_search%5Bsort_column%5D=revised_at&work_search%5Bother_tag_names%5D=&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=zh&commit=Sort+and+Filter&tag_id=Fantastics+from+Exile+Tribe+%28Band%29'

[[feeds]]
name = 'EXILE (Japan Band)'
url = 'https://archiveofourown.org/works?work_search%5Bsort_column%5D=revised_at&work_search%5Bother_tag_names%5D=&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=zh&commit=Sort+and+Filter&tag_id=EXILE+%28Japan+Band%29'

[[feeds]]
name = 'J Soul Brothers (Band)'
url = 'https://archiveofourown.org/works?work_search%5Bsort_column%5D=revised_at&work_search%5Bother_tag_names%5D=&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=zh&commit=Sort+and+Filter&tag_id=J+Soul+Brothers+%28Band%29'

[[feeds]]
name = 'Sexy Zone (Band)'
url = 'https://archiveofourown.org/tags/Sexy%20Zone%20(Band)/works'

[[feeds]]
name = 'SixTONES (Band)'
url = 'https://archiveofourown.org/tags/SixTONES%20(Band)/works'

[[feeds]]
name = 'Hey! Say! JUMP (Band)'
url = 'https://archiveofourown.org/works?work_search%5Bsort_column%5D=revised_at&work_search%5Bother_tag_names%5D=&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=zh&commit=Sort+and+Filter&tag_id=Hey%21+Say%21+JUMP+%28Band%29'

[[feeds]]
name = 'HiGH&LOW: the Story of S.W.O.R.D. (TV)'
url = 'https://archiveofourown.org/works?work_search%5Bsort_column%5D=revised_at&work_search%5Bother_tag_names%5D=&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=zh&commit=Sort+and+Filter&tag_id=HiGH*a*LOW%3A+the+Story+of+S*d*W*d*O*d*R*d*D*d*+%28TV%29'

[[feeds]]
name = 'HiGH&LOW (Movies)'
url = 'https://archiveofourown.org/works?work_search%5Bsort_column%5D=revised_at&work_search%5Bother_tag_names%5D=&work_search%5Bexcluded_tag_names%5D=&work_search%5Bcrossover%5D=&work_search%5Bcomplete%5D=&work_search%5Bwords_from%5D=&work_search%5Bwords_to%5D=&work_search%5Bdate_from%5D=&work_search%5Bdate_to%5D=&work_search%5Bquery%5D=&work_search%5Blanguage_id%5D=zh&commit=Sort+and+Filter&tag_id=HiGH*a*LOW+%28Movies%29'

[[feeds]]
name = 'Sato Taiki:Yamamoto Sekai'
url = 'https://archiveofourown.org/tags/Sato%20Taiki*s*Yamamoto%20Sekai/works'
