[[feeds]]
name = 'Generations from Exile Tribe (Band)'
url = 'https://archiveofourown.org/tags/16861914/feed.atom'

[[feeds]]
name = 'The Rampage from Exile Tribe (Band)'
url = 'https://archiveofourown.org/tags/19984521/feed.atom'

[[feeds]]
name = 'Fantastics from Exile Tribe (Band)'
url = 'https://archiveofourown.org/tags/40234885/feed.atom'

[[feeds]]
name = 'EXILE (Japan Band)'
url = 'https://archiveofourown.org/tags/17343258/feed.atom'

[[feeds]]
name = 'J Soul Brothers (Band)'
url = 'https://archiveofourown.org/tags/12153406/feed.atom'

[[feeds]]
name = 'Sexy Zone (Band)'
url = 'https://archiveofourown.org/tags/65865229/feed.atom'

[[feeds]]
name = 'SixTONES (Band)'
url = 'https://archiveofourown.org/tags/5650746/feed.atom'

[[feeds]]
name = 'Hey! Say! JUMP (Band)'
url = 'https://archiveofourown.org/tags/65865400/feed.atom'

[[feeds]]
name = 'HiGH&LOW: the Story of S.W.O.R.D. (TV)'
url = 'https://archiveofourown.org/tags/21592518/feed.atom'

[[feeds]]
name = 'HiGH&LOW (Movies)'
url = 'https://archiveofourown.org/tags/21592494/feed.atom'

[[feeds]]
name = 'Sato Taiki:Yamamoto Sekai'
url = 'https://archiveofourown.org/tags/72641245/feed.atom'

[[feeds]]
name = 'Chinese Comedian RPF'
url = 'https://archiveofourown.org/tags/15453690/feed.atom'
